// Mocks generated by Mockito 5.4.6 from annotations
// in ghub_mobile/test/features/achievements/providers/achievement_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ghub_mobile/features/games/data/models/steam_achievement_model.dart'
    as _i6;
import 'package:ghub_mobile/features/games/data/models/steam_game_details_model.dart'
    as _i5;
import 'package:ghub_mobile/features/games/data/models/steam_game_model.dart'
    as _i4;
import 'package:ghub_mobile/features/games/data/services/steam_games_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SteamGamesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSteamGamesService extends _i1.Mock implements _i2.SteamGamesService {
  MockSteamGamesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.SteamGameModel>> getUserGames(
    String? steamId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserGames,
              [steamId],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i3.Future<List<_i4.SteamGameModel>>.value(
              <_i4.SteamGameModel>[],
            ),
          )
          as _i3.Future<List<_i4.SteamGameModel>>);

  @override
  _i3.Future<_i5.SteamGameDetailsModel?> getGameDetails(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#getGameDetails, [appId]),
            returnValue: _i3.Future<_i5.SteamGameDetailsModel?>.value(),
          )
          as _i3.Future<_i5.SteamGameDetailsModel?>);

  @override
  _i3.Future<Map<String, dynamic>?> getPlayerStats(
    String? steamId,
    String? appId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlayerStats, [steamId, appId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<_i4.SteamGameModel>> getRecentlyPlayedGames(
    String? steamId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyPlayedGames, [steamId]),
            returnValue: _i3.Future<List<_i4.SteamGameModel>>.value(
              <_i4.SteamGameModel>[],
            ),
          )
          as _i3.Future<List<_i4.SteamGameModel>>);

  @override
  _i3.Future<List<_i6.SteamAchievementModel>> getPlayerAchievements(
    String? steamId,
    String? appId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlayerAchievements, [steamId, appId]),
            returnValue: _i3.Future<List<_i6.SteamAchievementModel>>.value(
              <_i6.SteamAchievementModel>[],
            ),
          )
          as _i3.Future<List<_i6.SteamAchievementModel>>);

  @override
  _i3.Future<List<_i6.SteamAchievementSchemaModel>> getGameAchievementSchema(
    String? appId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGameAchievementSchema, [appId]),
            returnValue:
                _i3.Future<List<_i6.SteamAchievementSchemaModel>>.value(
                  <_i6.SteamAchievementSchemaModel>[],
                ),
          )
          as _i3.Future<List<_i6.SteamAchievementSchemaModel>>);

  @override
  _i3.Future<Map<String, double>> getGlobalAchievementPercentages(
    String? appId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGlobalAchievementPercentages, [appId]),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);

  @override
  _i3.Future<List<_i6.CompleteSteamAchievementModel>>
  getCompleteGameAchievements(String? steamId, String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#getCompleteGameAchievements, [steamId, appId]),
            returnValue:
                _i3.Future<List<_i6.CompleteSteamAchievementModel>>.value(
                  <_i6.CompleteSteamAchievementModel>[],
                ),
          )
          as _i3.Future<List<_i6.CompleteSteamAchievementModel>>);
}
