// Mocks generated by Mockito 5.4.6 from annotations
// in ghub_mobile/test/features/auth/domain/usecases/logout_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ghub_mobile/core/error/failure.dart' as _i5;
import 'package:ghub_mobile/features/auth/domain/entities/auth_result.dart'
    as _i6;
import 'package:ghub_mobile/features/auth/domain/entities/signup_request.dart'
    as _i7;
import 'package:ghub_mobile/features/auth/domain/entities/user.dart' as _i8;
import 'package:ghub_mobile/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResult>> signUp(
    _i7.SignUpRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [request]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AuthResult>(
                    this,
                    Invocation.method(#signUp, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResult>> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AuthResult>(
                    this,
                    Invocation.method(#loginWithGoogle, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.User?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.User?>>.value(
              _FakeEither_0<_i5.Failure, _i8.User?>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.User?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#isLoggedIn, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String?>> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String?>>.value(
              _FakeEither_0<_i5.Failure, String?>(
                this,
                Invocation.method(#getAccessToken, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String?>>);
}
