# Build runner configuration for code generation
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
      freezed:
        options:
          # Add any freezed-specific options here if needed